CUDA_VISIBLE_DEVICES=0 python train_graspnet.py \
--batch-size 4 \
--step-cnt 2 \
--lr 1e-2 \
--anchor-num 7 \
--anchor-k 6 \
--anchor-w 50 \
--anchor-z 20 \
--all-points-num 25600 \
--group-num 512 \
--center-num 128 \
--scene-l 0 \
--scene-r 100 \
--noise 0 \
--grid-size 8 \
--input-w 640 \
--input-h 360 \
--loc-a 1 \
--reg-b 5 \
--cls-c 1 \
--offset-d 1 \
--epochs 15 \
--ratio 8 \
--num-workers 1 \
--save-freq 1 \
--optim 'adamw' \
--dataset-path '/home/chkim/GRASP/hggd_data/realsense/6dto2drefine_realsense' \
--scene-path '/home/chkim/GRASP/GraspNet1Billiion/scene_data' \
--description 'realsense' \
--joint-trainning \
--wandb-key 'ead4e17f10e71dced63d75d8841e02621ac32330' \
--wandb-project-name 'GRASP_based_on_HGGD'

